export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const POST_LEADERBOARD_START = 'POST_LEADERBOARD_START';
export const POST_LEADERBOARD_SUCCESS = 'POST_LEADERBOARD_SUCCESS';
export const POST_LEADERBOARD_FAIL = 'POST_LEADERBOARD_FAIL';

export const CREATE_PUZZLE = 'CREATE_PUZZLE';
export const CLEAR_PUZZLE = 'CLEAR_PUZZLE';
export const DELETE_PUZZLE_START = 'DELETE_PUZZLE_START';
export const DELETE_PUZZLE_SUCCESS = 'DELETE_PUZZLE_SUCCESS';
export const DELETE_PUZZLE_FAIL = 'DELETE_PUZZLE_FAIL';

export const CREATE_MODAL = 'CREATE_MODAL';
export const DESTROY_MODAL = 'DESTROY_MODAL';

export const SAVE_PUZZLE_START = 'SAVE_PUZZLE_START';
export const SAVE_PUZZLE_SUCCESS = 'SAVE_PUZZLE_SUCCESS';
export const SAVE_PUZZLE_FAIL = 'SAVE_PUZZLE_FAIL';

export const GET_PUZZLE_START = 'GET_PUZZLE_START';
export const GET_PUZZLE_SUCCESS = 'GET_PUZZLE_SUCCESS';
export const GET_PUZZLE_FAIL = 'GET_PUZZLE_FAIL';

export const GAME_PUZZLE_INPUT = 'GAME_PUZZLE_INPUT';
export const GAME_INIT_TIME = 'GAME_INIT_TIME';
export const GAME_UPDATE_TIME = 'GAME_UPDATE_TIME';
export const GAME_PUZZLE_HIGHLIGHT = 'GAME_PUZZLE_HIGHLIGHT';
